# Generated by Django 5.1.5 on 2026-09-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.PositiveIntegerField()),
                ('variant_label', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('tv', 'TV'), ('radio', 'Radio'), ('direct_mail', 'Direct Mail')], max_length=32)),
                ('created_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeRefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_requests', to='creatives.creativeasset')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativePerformanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fatigue_score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='creatives.creativeasset')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('creative', 'date')},
            },
        ),
    ]
