# Generated by Django 5.1.5 on 2026-09-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.PositiveIntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation', models.JSONField()),
                ('rationale', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Daypart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('tv', 'TV'), ('radio', 'Radio')], max_length=16)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.PositiveIntegerField()),
                ('air_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creative_label', models.CharField(blank=True, max_length=50)),
                ('daypart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spots.daypart')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spots.station')),
            ],
            options={
                'ordering': ['air_date'],
            },
        ),
        migrations.CreateModel(
            name='SpotPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('cpl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='spots.spot')),
            ],
        ),
    ]
