# Generated by Django 5.1.5 on 2026-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecommendation',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetrecommendation',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
