# Generated by Django 5.1.5 on 2026-09-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vertical', models.CharField(choices=[('medicare_advantage', 'Medicare Advantage'), ('insurance', 'Insurance'), ('home_services', 'Home Services')], max_length=32)),
                ('channel', models.CharField(choices=[('tv', 'TV'), ('radio', 'Radio'), ('direct_mail', 'Direct Mail')], max_length=32)),
                ('target_cpl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPerformanceRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leads', models.PositiveIntegerField()),
                ('calls', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('cpl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
