# Generated by Django 5.1.5 on 2026-09-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAgentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vertical_specialty', models.CharField(choices=[('medicare_advantage', 'Medicare Advantage'), ('insurance', 'Insurance'), ('home_services', 'Home Services')], max_length=32)),
                ('historical_conversion_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_certified_medicare', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('wait_time_seconds', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('conversion', 'Conversion'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail'), ('dropped', 'Dropped')], max_length=16)),
                ('routed_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_events', to='calls.clientagentpool')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='calls.clientagentpool')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
